Footer
stelmakh1991/DreamTeamGoIT-project-21 pull request #1
Opened 2023-10-28 16:02 UTC by SerhiyChynin

Привіт, наче все зробив, треба узгодити назви айдішників для якорів, щоб були однакові, і вписати в html, я від себе поки написав по назвах посилань. Також поставив у боді бекграунд колор щоб було видно що я роблю і обнулив марджини у боді, заважали правильно геометрію виставити, треба буде прибрати.

2023-10-29 12:56 UTC, OlehKotov reviewed
Validator

2023-10-29 12:56 UTC, OlehKotov commented on src/partials/footer.html
> -<footer class="container">
Validator

2023-10-29 12:56 UTC, OlehKotov commented on src/css/footer.css
.footer-link-list {
    margin-bottom: 115px;  на 1280 та 1440 в макете 117px

2023-10-29 12:56 UTC, OlehKotov commented on src/css/footer.css
>          line-height: 1.16;
Цей font-size та line-height вже прописан на 1280

та .footer-link-list {
        margin-bottom: 115px;
        gap: 25px;
    } теж повторються на 1280та 1440

2023-10-29 18:05 UTC, SerhiyChynin commented on src/partials/footer.html
> -<footer class="container">
Validator ругается что нет html разметки, doctype и тд, но он есть в мейн, поэтому нет смысла его дублировать, но дальше со списком есть нюанс у меня, доработаю

2023-10-30 07:12 UTC, OlehKotov commented on src/partials/footer.html
> -<footer class="container">
Validator ругается что нет html разметки, doctype, это у всех. Я имел ввиду список.

2023-10-30 09:01 UTC, stelmakh1991 commented on src/partials/footer.html
> +                            <a href="#about_us">About us</a>
#about-us

2023-10-30 09:01 UTC, stelmakh1991 commented on src/partials/footer.html
> +                            <a href="#our_collection">Our collection</a>
#our-collection

2023-10-30 09:01 UTC, stelmakh1991 commented on src/partials/footer.html
> +                            <a href="#customer_oreder">CUSTOMER ORDER</a>
#customer-order

2023-10-30 09:01 UTC, stelmakh1991 commented on src/css/footer.css
>      max-width: 375px;
max-width - видали

2023-10-30 09:01 UTC, stelmakh1991 commented on src/css/footer.css
>      margin: 0 auto;
видали

2023-10-30 09:01 UTC, stelmakh1991 commented on src/css/footer.css
>      margin: 0;
margin: 0; зайве

2023-10-30 09:01 UTC, stelmakh1991 commented on src/css/footer.css
>      display: flex;
display: flex; не потрібно

2023-10-30 09:01 UTC, stelmakh1991 commented on src/css/footer.css
> +    line-height: 1.29;
допиши transition: color 250ms cubic-bezier(0.4, 0, 0.2, 1);

2023-11-01 10:45 UTC, stelmakh1991 requested changes

2023-11-01 10:45 UTC, stelmakh1991 commented on src/css/footer.css
> +.footer-container{
це треба для футера напряму задати

2023-11-01 10:45 UTC, stelmakh1991 commented on src/css/footer.css
> +    background-image: url(../img/footer/mobile/emblem-mob.png);
background-image: url("../img/footer/mobile/emblem-mob.png");

2023-11-01 10:45 UTC, stelmakh1991 commented on src/css/footer.css
> +    line-height: 1.185;
width: 521px;
текст вирівняєш падінгом правим

2023-11-01 10:45 UTC, stelmakh1991 commented on src/css/footer.css
> +    line-height: 1.156;
width: 754px;

2023-11-01 20:03 UTC, stelmakh1991 approved these changes

2023-11-01 20:03 UTC, merged