Testimonials
stelmakh1991/DreamTeamGoIT-project-21 pull request #2
Opened 2023-10-29 13:10 UTC by Feniuk

2023-10-29 17:12 UTC, OlehKotov commented on src/partials/testimonials.html
> +                <img src="./img/testimonials/Ellipse1.jpg" alt="Maria Tkachuk" width="64" height="64" class="testimonials-maria">
Треба  ще прописати img під 2х, через srcset

2023-10-29 17:12 UTC, OlehKotov commented on src/css/testimonials.css
> +    padding: 0 18px 18px 18px;
нема border-radius: 4px;
border: 1px solid rgba(252, 249, 249, 0.10);

2023-10-29 17:12 UTC, OlehKotov commented on src/css/testimonials.css
> +    max-width: 291px;
текст .testimonials-text не відображається так як на макеті

2023-10-29 17:12 UTC, OlehKotov commented on src/css/testimonials.css
background-color: #1C2225;; дві точки с запятой, та на мою думку бєкгр колор краще перенести на testimonials, так при розширювані екрану колір фону завжди на всю ширину екрану.
Нема нижнього відступу до футера.

2023-10-30 07:53 UTC, stelmakh1991 commented on src/css/testimonials.css
> +    width: 64px;
width: auto;
height: auto;

2023-10-30 07:53 UTC, stelmakh1991 commented on src/css/testimonials.css
>      transform: translate(-50%);
transform: translateY (-50%);

2023-10-30 07:53 UTC, stelmakh1991 commented on src/css/testimonials.css
> +        max-width: 768px;
видали max-width для контейнера з усіх медіазапитів, я пропишу його у загальних стилях

2023-10-30 07:53 UTC, stelmakh1991 commented on src/css/testimonials.css
> +        row-gap: normal;
для чого row-gap??? воно зайве

2023-10-30 07:53 UTC, stelmakh1991 commented on src/css/testimonials.css
> +        max-width: 1440px;
видали

2023-10-30 07:53 UTC, stelmakh1991 commented on src/css/testimonials.css
> +        max-width: 1280px;
видали

2023-10-30 07:53 UTC, stelmakh1991 commented on src/partials/testimonials.html
> +                <img src="./img/testimonials/Ellipse1.jpg" alt="Maria Tkachuk" width="64" height="64" class="testimonials-maria">
srcset пиши перед src

2023-11-01 20:21 UTC, stelmakh1991 requested changes

2023-11-01 20:21 UTC, stelmakh1991 commented on src/css/testimonials.css
> +    .testimonials-list{
justify-content: center;

2023-11-01 20:21 UTC, stelmakh1991 commented on src/css/testimonials.css
> +    margin-bottom: 80px;
padding-bottom: 80px;

2023-11-02 13:53 UTC, stelmakh1991 approved these changes

2023-11-02 13:57 UTC, merged