add section "Our collection" (html&css)
stelmakh1991/DreamTeamGoIT-project-21 pull request #6
Opened 2023-10-30 12:17 UTC by Maryna-Danyliuk

Added "our collection" section. The section has html markup, namely the added list of collection elements. The list has been designed and 2x images have been added. Also included is a background embroidery.

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(min-width:1280px)"
media="(min-width:1440px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(min-width:1280px)"
media="(min-width:1440px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(min-width:768px)"
media="(min-width:1280px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(max-width:767px)"
media="(min-width:768px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(min-width:1280px)"
media="(min-width:1440px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(min-width:768px)"
media="(min-width:1280px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(max-width:767px)"
media="(min-width:768px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(min-width:1280px)"
media="(min-width:1440px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(min-width:768px)"
media="(min-width:1280px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(max-width:767px)"
media="(min-width:768px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(min-width:1280px)"
media="(min-width:1440px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(min-width:768px)"
media="(min-width:1280px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(max-width:767px)"
media="(min-width:768px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(min-width:1280px)"
media="(min-width:1440px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(min-width:768px)"
media="(min-width:1280px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/partials/our_collection.html
> +            media="(max-width:767px)"
media="(min-width:768px)"

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +}
.container {
  box-sizing: border-box;
}
@media screen and (min-width: 768px) {
  .container {
    min-width: 768px;
  }
} 
ВИДАЛИ

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +}
@media screen and (min-width: 1280px) {
  .container {
    min-width: 1280px;
  }
видали
}

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +  box-sizing: border-box;
box-sizing: border-box; зайве

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +  padding-top: 18px;
padding-top: 18px; не потрібно

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +    padding-top: 50px;
padding-top: 50px; непотрібно

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +  background-position-y: 300px;
background-position-y: 298px;

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +    background-position-y: 300px;
background-position-y: 221px;

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +    background-position-y: 270px;
background-position-y: 270px; - видали

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +  letter-spacing: -0.96px;
font-size: 32px;
  font-weight: 500;
  line-height: 1.38;
  letter-spacing: -0.96px; 
видали

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +    letter-spacing: -1.32px;
letter-spacing: -0.08em;

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +    /* width: calc(100%-20px) / 2; */
width: 342px; - видали

width: calc((100%-20px) / 2);

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +    width: 347px;
width: calc((100%-40px) / 3);

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +  letter-spacing: 0.7px;
letter-spacing: 0.04em;

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +  letter-spacing: 0.7px;
letter-spacing: 0.04em;

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +  width: 335px;
@media screen and (min-width: 375px) {
    .collection-photo {
                 width: 335px;
     }
}

2023-10-31 19:51 UTC, stelmakh1991 commented on src/css/our_collection.css
> +  width: 335px;
width: 335px; видали

2023-11-01 06:53 UTC, stelmakh1991 requested changes
якщо поправила відправ

2023-11-01 07:21 UTC, Maryna-Danyliuk reviewed
Our collection

2023-11-01 10:20 UTC, stelmakh1991 requested changes
погуртуй медіазапити однакові в один

2023-11-01 11:58 UTC, stelmakh1991 requested changes
впиши усі медіа 768 у одному медіазапиті, як у прикладі, і таким же чином заміни 1280 і 1440, щоб на кожне розширення було по одному медіазапиту

2023-11-01 11:58 UTC, stelmakh1991 commented on src/css/our_collection.css
> +    padding-top: 70px;
padding-top: 70px; - видали

2023-11-01 11:58 UTC, stelmakh1991 commented on src/css/our_collection.css
> +}
@media screen and (min-width: 768px) {
.collection-photo {
    width: 342px;
  }
.collection-price{
    font-size: 18px;
  }
.collection-name{
  font-size: 18px;
}
.collection-item {
    width: calc((100% - 20px) / 2);
  }
.collection-title {
    line-height: 1.45;
    font-size: 44px;
    letter-spacing: -0.03em;
  }
.collection {
    padding-bottom: 100px;
    background-position-y: 221px;
    background-image: url(../img/our_collection/tablet/emblem2-tab.png);
    background-size: 100px;
  }
}

2023-11-01 18:29 UTC, stelmakh1991 requested changes
background-color перестав з контейнера на секцію

2023-11-02 07:51 UTC, stelmakh1991 approved these changes

2023-11-02 07:51 UTC, merged