Your order
stelmakh1991/DreamTeamGoIT-project-21 pull request #7
Opened 2023-10-31 16:53 UTC by Chillbroz

Привіт, відправляю на узгодження

2023-11-01 07:03 UTC, stelmakh1991 requested changes
поправ кілька моментів

2023-11-01 07:03 UTC, stelmakh1991 commented on src/partials/your_order.html
> +                        <input type="text" class="form-input" name="user-name" id="user-name" placeholder="Enter your full name" />
<input type="text" class="form-input" name="user-name" id="user-name" placeholder="Enter your full name" required />

2023-11-01 07:03 UTC, stelmakh1991 commented on src/partials/your_order.html
> +                        <input type="email" class="form-input" name="user-email" id="user-email" placeholder="Enter your email" />
<input type="email" class="form-input" name="user-email" id="user-email" placeholder="Enter your email" required />

2023-11-01 07:03 UTC, stelmakh1991 commented on src/partials/your_order.html
> +                    <source srcset="../img/your_order/desctop1440/image1-desc1440.jpg 1x, ../img/your_order/desctop1440/image1-desc1440-2x.jpg 2x" media="(min-width: 1440px)">
<source srcset="../img/your_order/desctop1440/image1-desc1440.jpg 1x, ../img/your_order/desctop1440/image1-desc1440-2x.jpg 2x" media="(min-width: 1440px)" />

2023-11-01 07:03 UTC, stelmakh1991 commented on src/partials/your_order.html
> +                    <source srcset="../img/your_order/desctop/image1-desc.jpg 1x, ../img/your_order/desctop/image1-desc-2x.jpg 2x" media="(min-width: 1280px)">
<source srcset="../img/your_order/desctop/image1-desc.jpg 1x, ../img/your_order/desctop/image1-desc-2x.jpg 2x" media="(min-width: 1280px)" />

2023-11-01 07:03 UTC, stelmakh1991 commented on src/partials/your_order.html
> +                    <source srcset="../img/your_order/tablet/Image1-tab.jpg 1x, ../img/your_order/tablet/Image1-tab-2x.jpg 2x" media="(min-width: 768px)">
<source srcset="../img/your_order/tablet/Image1-tab.jpg 1x, ../img/your_order/tablet/Image1-tab-2x.jpg 2x" media="(min-width: 768px)" />

2023-11-01 07:03 UTC, stelmakh1991 commented on src/css/your_order.css
> +    min-width: 100%;
width: 100%;

2023-11-01 07:03 UTC, stelmakh1991 commented on src/css/your_order.css
> +    min-width: 100%;
width: 100%;

2023-11-01 07:52 UTC, Chillbroz commented
Виправив min-width на width у стилях.
Огорнув текст кнопки у спан, бо валідатор ругався на параграф. до инпутів додав pattern та required

2023-11-02 07:31 UTC, stelmakh1991 approved these changes

2023-11-02 07:31 UTC, merged